### ISSUE TITLE
Fresh install wd_s generator throws an error when attempting to generate a site

### ISSUE THREAD

**Issue by pmgarman** [WebDevStudios/generator-wd-s#5]
Cloning wd_s from GitHub...
ERROR CAUGHT: undefined
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

/usr/local/lib/node_modules/generator-wd-s/node_modules/yeoman-generator/node_modules/file-utils/lib/file.js:252
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e
          ^
Error: Unable to read "/usr/local/lib/node_modules/generator-wd-s/app/templates/package.json" file (Error code: ENOENT).
    at Env.File.read (/usr/local/lib/node_modules/generator-wd-s/node_modules/yeoman-generator/node_modules/file-utils/lib/file.js:252:11)
    at Env.(anonymous function) [as read] (/usr/local/lib/node_modules/generator-wd-s/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:24:41)
    at yeoman.generators.Base.extend.getFiles (/usr/local/lib/node_modules/generator-wd-s/app/index.js:119:40)
    at /usr/local/lib/node_modules/generator-wd-s/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)

**Comment by JayWood** [comment]
As a temporary fix, I went into `%appdata%/roamind/npm/node_modules` and disabled the read-only checkbox for `generator-wd-s`  But, I am on a **Windows** machine, so it could be UAC related.

**Comment by CamdenSegal** [comment]
This issue should now be fixed with 9c67f3e2a7a128fd42444dccadb3b2572255241d
